
--  PRODUCTO POR CODIGO DE INTERNET
SELECT  PRODUCT_ID 
FROM    ATGDB_PUB.GN_PRD_ATTR 
WHERE   1 = 1
    AND ATTRIBUTE_NAME = 'CODIGO_INTERNET' 
    AND ATTRIBUTE_VALUE = '565802'
GROUP BY PRODUCT_ID
--  --------


--  PRODUCTO POR PRODUCTO ID
SELECT  * 
FROM    ATGDB_PUB.DCS_PRODUCT 
WHERE   1 = 1
    AND PRODUCT_ID = '151684' 
    AND IS_HEAD = 1
--  --------

--  GN PRODUCTO POR PRODUCTO ID
SELECT  GN_P.* 
FROM    ATGDB_PUB.GN_PRODUCT GN_P
        INNER JOIN ATGDB_PUB.DCS_PRODUCT P ON P.PRODUCT_ID = GN_P.PRODUCT_ID AND P.ASSET_VERSION = GN_P.ASSET_VERSION
WHERE   1 = 1
    AND P.PRODUCT_ID = '151684'
    AND P.IS_HEAD = 1
--  --------


--  SKUS POR PRODUCTO ID
SELECT  S.*
FROM    ATGDB_PUB.DCS_SKU S
        INNER JOIN ATGDB_PUB.DCS_PRD_CHLDSKU PCS ON PCS.SKU_ID = S.SKU_ID AND PCS.SEC_ASSET_VERSION = S.ASSET_VERSION
        INNER JOIN ATGDB_PUB.DCS_PRODUCT P ON P.PRODUCT_ID = PCS.PRODUCT_ID AND P.ASSET_VERSION = PCS.ASSET_VERSION
WHERE   1 = 1
    AND P.PRODUCT_ID = '151684'
    AND P.IS_HEAD = 1
--  --------


--  INVENTARIO TOTAL POR SKU
SELECT  * 
FROM    ATGDB_CORE.DCS_INVENTORY 
WHERE   INVENTORY_ID LIKE 'inv_no_location' || '151684' || '%'
--  --------

--  INVENTARIO POR LOCALIDAD
SELECT  * 
FROM    ATGDB_CORE.DCS_INVENTORY 
WHERE   INVENTORY_ID LIKE '%' || '151684' || '%'
--  --------




--  TABLAS DE ASSETS 

SELECT P.* FROM ATGDB_PUB.DCS_PRODUCT P WHERE P.IS_HEAD = 1 AND P.PRODUCT_ID = '154470'
SELECT PPC.* FROM ATGDB_PUB.DCS_PRD_PRNT_CATS PPC WHERE PPC.PRODUCT_ID = '159231' AND PPC.ASSET_VERSION >= 1
SELECT PCS.* FROM ATGDB_PUB.DCS_PRD_CHLDSKU PCS WHERE PCS.PRODUCT_ID = '156761' AND PCS.ASSET_VERSION >= 10
SELECT CCP.* FROM ATGDB_aPUB.DCS_CAT_CHLDPRD CCP WHERE CCP.CHILD_PRD_ID = '159231' AND CCP.SEC_ASSET_VERSION >= 1
SELECT GN_P.* FROM ATGDB_PUB.GN_PRODUCT GN_P WHERE GN_P.PRODUCT_ID = '159231' AND GN_P.ASSET_VERSION >= 1
SELECT GN_PA.* FROM ATGDB_PUB.GN_PRD_ATTR GN_PA WHERE GN_PA.PRODUCT_ID = '154470' AND GN_PA.ASSET_VERSION >= 25


SELECT S.* FROM ATGDB_PUB.DCS_SKU S WHERE S.IS_HEAD = 1 AND SKU_ID LIKE '150141%'
SELECT M.* FROM ATGDB_PUB.DBC_MEASUREMENT M WHERE SKU_ID LIKE '150141%' AND ASSET_VERSION >= 3
SELECT GN_S.* FROM ATGDB_PUB.GN_SKU GN_S WHERE GN_S.SKU_ID LIKE '150141%' AND ASSET_VERSION >= 3

        
SELECT C.* FROM ATGDB_PUB.DCS_CATEGORY C WHERE C.IS_HEAD = 1 AND C.CATEGORY_ID = '1030201'
SELECT CCC.* FROM ATGDB_PUB.DCS_CAT_CHLDCAT CCC WHERE CCC.CHILD_CAT_ID = '1030201' AND SEC_ASSET_VERSION >= 400
SELECT CC.* FROM ATGDB_PUB.DCS_CAT_CATALOGS CC WHERE CC.CATEGORY_ID = '1030201' AND ASSET_VERSION >= 400
SELECT CS.* FROM ATGDB_PUB.DCS_CATEGORY_SITES CS WHERE CS.CATEGORY_ID = '1030201' AND ASSET_VERSION >= 400
SELECT CCP.* FROM ATGDB_PUB.DCS_CAT_CHLDPRD CCP WHERE CCP.CATEGORY_ID = '1030201' AND ASSET_VERSION >= 400

--  --------