
--  ORDENES POR MEMBERSHIP
SELECT  * 
FROM    ATGDB_CORE.DCSPP_ORDER 
WHERE   1 = 1
    AND PROFILE_ID = 
        (
            SELECT  ID 
            FROM    GN_USER 
            WHERE   MEMBERSHIP_NUMBER = '1118337408'
        )
ORDER BY ORDER_ID DESC
--  --------


--  ORDEN POR ORDEN ID
SELECT  * 
FROM    ATGDB_CORE.DCSPP_ORDER 
WHERE   1 = 1
    AND ORDER_ID = '3723244'
--  --------

--  ORDEN POR ORDEN ID
SELECT  * 
FROM    ATGDB_CORE.GNDCSPP_ORDER 
WHERE   1 = 1
    AND ORDER_ID = '3723244'
--  --------


--  ORDEN POR ORDEN ID
SELECT  * 
FROM    DCSPP_ORDER_PRICE 
        INNER JOIN DCSPP_AMTINFO_ADJ AIA ON AIA.AMOUNT_INFO_ID = I.PRICE_INFO
        INNER JOIN DCSPP_PRICE_ADJUST PA ON PA.ADJUSTMENT_ID = AIA.ADJUSTMENTS
WHERE   1 = 1
    AND AMOUNT_INFO_ID = 
        (
            SELECT  PRICE_INFO 
            FROM    ATGDB_CORE.DCSPP_ORDER 
            WHERE   ORDER_ID = '3723244'
        )
--  --------



SELECT * FROM DCSPP_ORDER_ITEM WHERE ORDER_ID = '5092345'
SELECT * FROM DCSPP_ORDER_PRICE WHERE AMOUNT_INFO_ID = 'ai9372845'



SELECT PAYMENT_GROUPS FROM DCSPP_ORDER_PG WHERE ORDER_ID = '5541216'
SELECT * FROM DCSPP_PAY_GROUP WHERE ORDER_REF = '5541216'



SELECT * FROM DCSPP_ORDER_SG WHERE ORDER_ID = '5541216'
SELECT * FROM DCSPP_SHIP_GROUP WHERE ORDER_REF = '5541216'
SELECT * FROM DCSPP_SHIP_ADDR WHERE SHIPPING_GROUP_ID IN
(SELECT SHIPPING_GROUP_ID FROM DCSPP_SHIP_GROUP WHERE ORDER_REF = '5541216')



SELECT  O.ORDER_ID
        ,O.CREATION_DATE
        ,IP.*
        ,PA.*
FROM    DCSPP_ORDER O
        INNER JOIN DCSPP_ITEM I ON I.ORDER_REF = O.ORDER_ID
        INNER JOIN DCSPP_ITEM_PRICE IP ON IP.AMOUNT_INFO_ID = I.PRICE_INFO
        INNER JOIN DCSPP_AMTINFO_ADJ AIA ON AIA.AMOUNT_INFO_ID = I.PRICE_INFO
        INNER JOIN DCSPP_PRICE_ADJUST PA ON PA.ADJUSTMENT_ID = AIA.ADJUSTMENTS
WHERE   O.CREATION_DATE >= DATE '2019-11-01'
    AND (
            IP.ORDER_DISCOUNT <> 0 
        OR  IP.QTY_DISCOUNTED <> 0 
        OR  IP.QTY_WITH_FRACTION_DISCOUNTED <> 0
        OR  IP.QTY_AS_QUALIFIER <> 0
        OR  IP.QTY_WITH_FRACTION_AS_QUALIFIER <> 0
        )
ORDER BY ORDER_ID, I.PRICE_INFO, PA.ADJUSTMENT_ID


SELECT  MAX(CREATION_DATE), O.PROFILE_ID, GNU.MEMBERSHIP_NUMBER, OU.CUSTOMER_ID
FROM    DCSPP_ORDER O
        LEFT JOIN GN_USER GNU ON GNU.ID = O.PROFILE_ID
        LEFT JOIN ORCE_USER OU ON OU.MEMBERSHIP_ID = GNU.MEMBERSHIP_NUMBER
WHERE   O.PROFILE_ID IN (
        SELECT  PROFILE_ID
        FROM    DCSPP_ORDER 
        WHERE   STATE = 'INCOMPLETE'
            AND CREATION_DATE < TO_DATE('2019-08-13', 'YYYY-MM-DD')
        )
    AND O.CREATION_DATE > (
        SELECT  MAX(CREATION_DATE)
        FROM    DCSPP_ORDER 
        WHERE   STATE = 'INCOMPLETE'
            AND PROFILE_ID = O.PROFILE_ID
            AND CREATION_DATE < TO_DATE('2019-08-13', 'YYYY-MM-DD')
        )
    AND O.STATE = 'PROCESSING'
GROUP BY O.PROFILE_ID, GNU.MEMBERSHIP_NUMBER, OU.CUSTOMER_ID
